"""
strategy.py — Last-Second Momentum Strategy

Logic:
1. Monitor BNB price throughout the 5-minute window.
2. In the last `entry_window_seconds` of the window, compute P(Up).
3. Compare P(Up) to Polymarket's YES price.
4. If edge = |P(Up) - yes_price| > edge_threshold → signal a trade.
5. Size position using Kelly Criterion (fractional).

All calculations are pure functions for easy unit testing.
"""

import logging
import math
import time
from dataclasses import dataclass
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Data structures
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Signal:
    """A trading signal generated by the strategy."""

    side: str                  # "YES" or "NO"
    edge: float                # Our edge over Polymarket's price
    p_up: float                # Our estimated P(BNB goes up)
    yes_price: float           # Polymarket's YES price at signal time
    kelly_fraction: float      # Raw Kelly fraction (before capping)
    position_size_usdc: float  # Recommended position size in USDC
    timestamp: float           # Signal generation time
    is_mock: bool = False      # True if based on mock data
    bull_pct: float = 0.0      # Pool bull % at signal time
    bear_pct: float = 0.0      # Pool bear % at signal time

    def __repr__(self):
        return (
            f"Signal({self.side} | edge={self.edge:.3f} | "
            f"P(Up)={self.p_up:.3f} vs PM={self.yes_price:.3f} | "
            f"size=${self.position_size_usdc:.2f})"
        )


@dataclass
class WindowInfo:
    """Information about the current PancakeSwap epoch / betting window."""

    window_start_ts: float     # Unix timestamp of round start (start_ts from contract)
    window_end_ts: float       # Unix timestamp of lock (lock_ts from contract — betting deadline)
    seconds_remaining: float   # Seconds until lock_ts (betting closes)
    window_index: int          # Epoch number (from contract)
    entry_window_seconds: float = 60.0  # How many seconds before lock is "entry window"

    @property
    def is_entry_window(self) -> bool:
        """True if we're in the last N seconds before lock (entry zone)."""
        return self.seconds_remaining <= self.entry_window_seconds

    @property
    def progress_pct(self) -> float:
        """How far through the betting window we are (0.0 → 1.0)."""
        duration = self.window_end_ts - self.window_start_ts
        if duration <= 0:
            return 1.0
        elapsed = time.time() - self.window_start_ts
        return min(1.0, elapsed / duration)


# ─────────────────────────────────────────────────────────────────────────────
# Pure calculation functions (unit-testable)
# ─────────────────────────────────────────────────────────────────────────────

def window_from_round(round_data, entry_window_seconds: float = 60.0) -> WindowInfo:
    """
    Build a WindowInfo from PancakeSwap contract round data.

    Args:
        round_data: PancakeRound instance (from pancake.py).
        entry_window_seconds: How many seconds before lock_ts counts as entry window.

    Returns:
        WindowInfo populated from the round's start_ts, lock_ts, and epoch.
    """
    now = time.time()
    seconds_remaining = max(0.0, round_data.lock_ts - now)

    return WindowInfo(
        window_start_ts=float(round_data.start_ts),
        window_end_ts=float(round_data.lock_ts),
        seconds_remaining=seconds_remaining,
        window_index=round_data.epoch,
        entry_window_seconds=entry_window_seconds,
    )


def get_current_window(now: Optional[float] = None) -> WindowInfo:
    """
    Compute a clock-aligned 5-minute window (fallback / legacy use only).

    Prefer window_from_round() when PancakeSwap round data is available,
    as it uses the contract's actual start_ts and lock_ts.

    BNB Up/Down 5mn windows are aligned to UTC 5-minute marks:
    00:00, 00:05, 00:10, ...

    Returns:
        WindowInfo with start/end timestamps and seconds remaining.
    """
    if now is None:
        now = time.time()

    window_duration = 300  # 5 minutes
    window_start = int(now / window_duration) * window_duration
    window_end = window_start + window_duration
    seconds_remaining = window_end - now
    window_index = int(window_start / window_duration)

    return WindowInfo(
        window_start_ts=float(window_start),
        window_end_ts=float(window_end),
        seconds_remaining=seconds_remaining,
        window_index=window_index,
    )


def compute_momentum(prices: list[float]) -> float:
    """
    Compute simple momentum: (last_price / first_price) - 1.

    Args:
        prices: List of prices in chronological order.

    Returns:
        Momentum as a fraction (e.g., 0.005 = +0.5%).
        Returns 0.0 if fewer than 2 prices.
    """
    if len(prices) < 2:
        return 0.0
    return (prices[-1] / prices[0]) - 1.0


def compute_volatility(prices: list[float]) -> float:
    """
    Compute realized volatility (std dev of log returns).

    Args:
        prices: List of prices in chronological order.

    Returns:
        Annualized volatility estimate (per-observation std dev here).
        Returns 0.0 if fewer than 3 prices.
    """
    if len(prices) < 3:
        return 0.0
    log_returns = np.diff(np.log(prices))
    return float(np.std(log_returns))


def estimate_p_up_momentum(
    prices: list[float],
    window_seconds: float = 300.0,
    seconds_remaining: float = 60.0,   # DEPRECATED — kept for compat, no longer used
    seconds_to_lock: float = 30.0,     # NEW: seconds until lock_ts (end of bet phase)
    round_duration: float = 300.0,     # NEW: duration of live round post-lock (seconds)
    n_simulations: int = 500,
) -> float:
    """
    Estimate P(close_price > lock_price) for the current PancakeSwap round.

    PancakeSwap settles UP if close_price > lock_price, where:
      - lock_price  = oracle price at the moment betting closes (lock_ts)
      - close_price = oracle price at the end of the live round (close_ts)

    Method: Geometric Brownian Motion (GBM) Monte Carlo.
    We simulate a single continuous path from NOW through lock_ts and on to
    close_ts.  P(UP) = fraction of paths where close_price > lock_price.

    Args:
        prices: Price series observed since the start of the current epoch.
        window_seconds: Total betting window duration (unused, kept for compat).
        seconds_remaining: DEPRECATED — superseded by seconds_to_lock.
        seconds_to_lock: Seconds from now until lock_ts (betting deadline).
        round_duration: Duration of the live round after lock_ts (default 300s).
        n_simulations: Number of Monte Carlo paths.

    Returns:
        P(close > lock), clamped to [0.35, 0.65].
        Returns 0.5 if insufficient data.
    """
    if len(prices) < 5:
        logger.debug("Insufficient price data for GBM — returning 0.5")
        return 0.5

    # Observed drift and vol over the window so far
    log_returns = np.diff(np.log(prices))
    if len(log_returns) == 0:
        return 0.5

    mu = float(np.mean(log_returns))    # Per-second drift (1 obs ≈ 1s)
    sigma = float(np.std(log_returns))  # Per-second vol

    if sigma == 0:
        # No volatility: slight directional bias, never certainty
        if prices[-1] > prices[0]:
            return 0.6
        elif prices[-1] < prices[0]:
            return 0.4
        else:
            return 0.5

    current_price = prices[-1]

    # Simulate a single continuous path: NOW → lock_ts → close_ts
    # Each step = 1 second (dt = 1.0)
    total_seconds = seconds_to_lock + round_duration
    steps = max(2, int(total_seconds))  # at least 2 steps to have a lock and close
    lock_step = max(1, int(seconds_to_lock))  # index of the lock price in the path

    rng = np.random.default_rng()
    z = rng.standard_normal((n_simulations, steps))
    # Per-second log-increment: (mu - 0.5*sigma^2)*dt + sigma*sqrt(dt)*z, dt=1
    log_increments = (mu - 0.5 * sigma**2) + sigma * z
    cumulative = np.cumsum(log_increments, axis=1)

    # Price at lock_ts = current_price * exp(cumulative at step lock_step)
    lock_prices = current_price * np.exp(cumulative[:, lock_step - 1])

    # Price at close_ts = current_price * exp(cumulative at final step)
    close_prices = current_price * np.exp(cumulative[:, -1])

    # P(UP) = P(close_price > lock_price)
    p_up_raw = float(np.mean(close_prices > lock_prices))

    # Clamp to [0.35, 0.65] — force humility on 5min crypto direction.
    p_up = max(0.35, min(0.65, p_up_raw))

    logger.debug(
        f"GBM estimate: μ={mu:.6f} σ={sigma:.6f} "
        f"seconds_to_lock={seconds_to_lock:.0f}s round_duration={round_duration:.0f}s "
        f"steps={steps} lock_step={lock_step} "
        f"P(close>lock)={p_up:.3f} (raw={p_up_raw:.3f})"
    )
    return p_up


def compute_edge(p_up: float, yes_price: float) -> tuple[float, str]:
    """
    Compute the edge of a potential trade.

    Edge = |P(Up) - yes_price| — difference between our estimate and market price.
    Side = "YES" if we think it'll go up more than the market, "NO" otherwise.

    Args:
        p_up: Our estimated probability that BNB goes up.
        yes_price: Polymarket's YES price (= market-implied P(Up)).

    Returns:
        (edge, side) — edge as a positive float, side as "YES" or "NO".
    """
    if p_up > yes_price:
        return p_up - yes_price, "YES"
    else:
        return yes_price - p_up, "NO"


def kelly_fraction(p: float, odds: float = 1.0) -> float:
    """
    Compute the Kelly fraction for a binary bet.

    Kelly formula: f = p - q/b
    For a binary market with odds b (payout per unit risked = 1/price - 1):

    If YES at price `yes_price`:
      b = (1 - yes_price) / yes_price  (net profit per unit staked)
      f = (p * b - (1-p)) / b = (p*b - q) / b

    Args:
        p: Our estimated probability of winning.
        odds: Net odds (b = payout per unit risked, b=1.0 means evens).

    Returns:
        Kelly fraction (can be negative → no bet).
    """
    q = 1.0 - p
    if odds <= 0:
        return 0.0
    return (p * odds - q) / odds


def compute_position_size(
    edge: float,
    p_up: float,
    side: str,
    yes_price: float,
    bankroll: float,
    position_size_usdc: float = 10.0,
    min_usdc: float = 0.0,
    max_bankroll_pct: float = 1.0,
    max_pool_pct: float = 1.0,
    pool_total_usdc: float = 0.0,
    # Kept for backward compatibility — ignored
    kelly_fraction_cap: float = 0.25,
) -> tuple[float, float]:
    """
    Compute recommended position size using a flat fixed size with guards.

    Args:
        edge: Our edge (|P(Up) - yes_price|) — not used for sizing, kept for compat.
        p_up: Our P(Up) estimate — not used for sizing, kept for compat.
        side: "YES" or "NO" — not used for sizing, kept for compat.
        yes_price: Market YES price — not used for sizing, kept for compat.
        bankroll: Current bankroll in USDC.
        position_size_usdc: Flat position size (default $10).
        min_usdc: Minimum position size in USDC. If position falls below
            this threshold, the trade is skipped (returns 0.0).
        max_bankroll_pct: Cap as fraction of bankroll (e.g. 0.10 = 10%).
        max_pool_pct: Cap as fraction of pool total value in USDC (e.g. 0.10 = 10%).
            Only applied when pool_total_usdc > 0.
        pool_total_usdc: Total pool value in USDC (pool_total_bnb × bnb_price).
            When 0, the pool% cap is skipped.
        kelly_fraction_cap: Ignored — kept for backward-compatible call sites.

    Returns:
        (0.0, position_size_usdc)  — kelly_fraction field always 0.0 (log compat).
        position_size_usdc is 0.0 when position < min_usdc (trade skipped).
    """
    # Flat position size
    position = position_size_usdc

    # Apply caps: bankroll%, pool%
    caps = [bankroll * max_bankroll_pct]
    if pool_total_usdc > 0:
        caps.append(pool_total_usdc * max_pool_pct)
    position = min(position, *caps)

    # Skip if below minimum
    if position < min_usdc:
        return 0.0, 0.0

    position = max(0.0, round(position, 2))
    return 0.0, position


# ─────────────────────────────────────────────────────────────────────────────
# Strategy engine (legacy — kept for backward compat; new strategies in src/strategies/)
# ─────────────────────────────────────────────────────────────────────────────

class Strategy:
    """
    Last-Second Momentum Strategy for BNB Up/Down 5mn.

    Workflow:
    1. Called periodically by main loop with current price data + order book.
    2. Checks if we're in the entry window (last 60s).
    3. Estimates P(Up) via GBM Monte Carlo.
    4. Computes edge vs Polymarket price.
    5. Returns a Signal if edge exceeds threshold.
    """

    FAIR_ODDS_PRICE = 0.50  # Neutral price used when use_fair_odds=True

    def __init__(self, config: dict):
        cfg = config.get("strategy", {})
        self.edge_threshold = cfg.get("edge_threshold", 0.05)
        self.position_size_usdc = cfg.get("position_size_usdc", 10.0)
        self.min_position_usdc = cfg.get("min_position_usdc", 5.0)
        self.max_bankroll_pct = cfg.get("max_bankroll_pct", 1.0)
        self.max_pool_pct = cfg.get("max_pool_pct", 1.0)
        self.entry_window_seconds = cfg.get("entry_window_seconds", 60)
        self.min_prob_diff = cfg.get("min_prob_diff", 0.03)
        self.bankroll = cfg.get("starting_bankroll_usdc", 1000.0)
        self.use_fair_odds = cfg.get("use_fair_odds", True)

        pcfg = config.get("pancake", {})
        self.max_bet_share_of_side = pcfg.get("max_bet_share_of_side", 0.10)
        self.min_pool_bnb = pcfg.get("min_pool_bnb", 5.0)

    def update_bankroll(self, new_bankroll: float):
        """Update the current bankroll after PnL changes."""
        self.bankroll = new_bankroll
        self.last_skip_reason: Optional[str] = None  # Set when evaluate() returns None

    def evaluate(
        self,
        prices: list[float],
        yes_price: float,
        window: WindowInfo,
        is_mock_data: bool = False,
        pool_total_bnb: float = 0.0,
        pool_bull_bnb: float = 0.0,
        pool_bear_bnb: float = 0.0,
    ) -> Optional[Signal]:
        """
        Evaluate whether to generate a trading signal.

        Args:
            prices: BNB price series for the current window.
            yes_price: Polymarket's current YES price.
            window: Current window information.
            is_mock_data: Whether the order book data is mock.
            pool_total_bnb: Total BNB in the pool (for size filter, only used when use_fair_odds=False).
            pool_bull_bnb: BNB on the bull side of the pool.
            pool_bear_bnb: BNB on the bear side of the pool.

        Returns:
            Signal if conditions met, None otherwise.
            When returning None, self.last_skip_reason is set with a human-readable reason.
        """
        self.last_skip_reason = None

        # Only trade in the last N seconds of the window
        if not window.is_entry_window and window.seconds_remaining > self.entry_window_seconds:
            logger.debug(
                f"Not in entry window (remaining={window.seconds_remaining:.1f}s)"
            )
            return None

        if len(prices) < 5:
            self.last_skip_reason = f"⏸ Not enough price data ({len(prices)} pts)"
            logger.debug("Insufficient price data for strategy evaluation.")
            return None

        # Estimate P(close > lock) via GBM Monte Carlo
        p_up = estimate_p_up_momentum(
            prices=prices,
            seconds_to_lock=window.seconds_remaining,
            round_duration=300.0,
        )

        # Pool quality filters (only when trading against real pool prices)
        if not self.use_fair_odds:
            if pool_total_bnb < self.min_pool_bnb:
                self.last_skip_reason = f"⏸ Pool too small ({pool_total_bnb:.2f} BNB < {self.min_pool_bnb:.1f} min)"
                logger.info(
                    f"Pool too small: {pool_total_bnb:.3f} BNB (min={self.min_pool_bnb:.1f}) — skipping"
                )
                return None

        # Fair-odds mode: use 0.50 as the reference price regardless of pool
        # This avoids fictitious PnL from 99/1 pool imbalances
        if self.use_fair_odds:
            effective_yes_price = self.FAIR_ODDS_PRICE
            if yes_price != self.FAIR_ODDS_PRICE:
                logger.info(
                    f"[INFO ONLY] Pool yes_price={yes_price:.4f} "
                    f"(ignored — use_fair_odds=true, trading at {self.FAIR_ODDS_PRICE:.2f})"
                )
        else:
            effective_yes_price = yes_price

        # Compute edge using effective price (fair odds or pool price)
        edge, side = compute_edge(p_up, effective_yes_price)

        logger.info(
            f"Strategy eval: P(Up)={p_up:.3f} | "
            f"effective_price={effective_yes_price:.3f} | "
            f"edge={edge:.3f} | side={side} | remaining={window.seconds_remaining:.1f}s"
        )

        # Check if edge exceeds threshold (strict >)
        if edge <= self.edge_threshold:
            self.last_skip_reason = f"⏸ Edge too low ({edge:.3f} ≤ {self.edge_threshold:.2f}) | P(Up)={p_up:.2f} | {side}"
            logger.debug(f"Edge {edge:.3f} < threshold {self.edge_threshold:.3f} — no signal")
            return None

        # Compute position size (flat sizing with guards)
        raw_k, pos_size = compute_position_size(
            edge=edge,
            p_up=p_up,
            side=side,
            yes_price=effective_yes_price,
            bankroll=self.bankroll,
            position_size_usdc=self.position_size_usdc,
            min_usdc=self.min_position_usdc,
            max_bankroll_pct=self.max_bankroll_pct,
            max_pool_pct=self.max_pool_pct,
        )

        if pos_size <= 0:
            logger.debug("Position size is 0 — no signal")
            return None

        if not self.use_fair_odds and prices:
            logger.debug(
                f"Pool filter check: bull={pool_bull_bnb:.4f} bear={pool_bear_bnb:.4f} "
                f"side={side} bet=${pos_size:.2f} @ price={prices[-1]:.2f}"
            )
            # Check opposite side has liquidity (no opponent = no profit even if we win)
            opposite_bnb = pool_bear_bnb if side == "YES" else pool_bull_bnb
            if opposite_bnb < 0.01:
                self.last_skip_reason = f"⏸ No counterparty ({'BEAR' if side == 'YES' else 'BULL'} side empty)"
                logger.info(
                    f"Opposite side empty: {'BEAR' if side == 'YES' else 'BULL'} = "
                    f"{opposite_bnb:.4f} BNB — no profit possible, skipping"
                )
                return None

            bet_bnb = pos_size / prices[-1]  # approximate BNB equivalent
            side_bnb = pool_bull_bnb if side == "YES" else pool_bear_bnb
            if side_bnb > 0 and bet_bnb / side_bnb > self.max_bet_share_of_side:
                self.last_skip_reason = f"⏸ Bet too large ({bet_bnb:.3f} BNB = {bet_bnb/side_bnb:.0%} of {side} side)"
                logger.info(
                    f"Bet too large for side: {bet_bnb:.4f} BNB = "
                    f"{bet_bnb/side_bnb:.1%} of {side} side ({side_bnb:.4f} BNB) "
                    f"(max={self.max_bet_share_of_side:.0%}) — skipping"
                )
                return None

        signal = Signal(
            side=side,
            edge=edge,
            p_up=p_up,
            yes_price=effective_yes_price,
            kelly_fraction=raw_k,
            position_size_usdc=pos_size,
            timestamp=time.time(),
            is_mock=is_mock_data,
        )

        logger.info(f"🎯 Signal generated: {signal}")
        return signal
