"""
strategy.py — Last-Second Momentum Strategy

Logic:
1. Monitor BNB price throughout the 5-minute window.
2. In the last `entry_window_seconds` of the window, compute P(Up).
3. Compare P(Up) to Polymarket's YES price.
4. If edge = |P(Up) - yes_price| > edge_threshold → signal a trade.
5. Size position using Kelly Criterion (fractional).

All calculations are pure functions for easy unit testing.
"""

import logging
import math
import time
from dataclasses import dataclass
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Data structures
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Signal:
    """A trading signal generated by the strategy."""

    side: str                  # "YES" or "NO"
    edge: float                # Our edge over Polymarket's price
    p_up: float                # Our estimated P(BNB goes up)
    yes_price: float           # Polymarket's YES price at signal time
    kelly_fraction: float      # Raw Kelly fraction (before capping)
    position_size_usdc: float  # Recommended position size in USDC
    timestamp: float           # Signal generation time
    is_mock: bool = False      # True if based on mock data

    def __repr__(self):
        return (
            f"Signal({self.side} | edge={self.edge:.3f} | "
            f"P(Up)={self.p_up:.3f} vs PM={self.yes_price:.3f} | "
            f"size=${self.position_size_usdc:.2f})"
        )


@dataclass
class WindowInfo:
    """Information about the current PancakeSwap epoch / betting window."""

    window_start_ts: float     # Unix timestamp of round start (start_ts from contract)
    window_end_ts: float       # Unix timestamp of lock (lock_ts from contract — betting deadline)
    seconds_remaining: float   # Seconds until lock_ts (betting closes)
    window_index: int          # Epoch number (from contract)
    entry_window_seconds: float = 60.0  # How many seconds before lock is "entry window"

    @property
    def is_entry_window(self) -> bool:
        """True if we're in the last N seconds before lock (entry zone)."""
        return self.seconds_remaining <= self.entry_window_seconds

    @property
    def progress_pct(self) -> float:
        """How far through the betting window we are (0.0 → 1.0)."""
        duration = self.window_end_ts - self.window_start_ts
        if duration <= 0:
            return 1.0
        elapsed = time.time() - self.window_start_ts
        return min(1.0, elapsed / duration)


# ─────────────────────────────────────────────────────────────────────────────
# Pure calculation functions (unit-testable)
# ─────────────────────────────────────────────────────────────────────────────

def window_from_round(round_data, entry_window_seconds: float = 60.0) -> WindowInfo:
    """
    Build a WindowInfo from PancakeSwap contract round data.

    Args:
        round_data: PancakeRound instance (from pancake.py).
        entry_window_seconds: How many seconds before lock_ts counts as entry window.

    Returns:
        WindowInfo populated from the round's start_ts, lock_ts, and epoch.
    """
    now = time.time()
    seconds_remaining = max(0.0, round_data.lock_ts - now)

    return WindowInfo(
        window_start_ts=float(round_data.start_ts),
        window_end_ts=float(round_data.lock_ts),
        seconds_remaining=seconds_remaining,
        window_index=round_data.epoch,
        entry_window_seconds=entry_window_seconds,
    )


def get_current_window(now: Optional[float] = None) -> WindowInfo:
    """
    Compute a clock-aligned 5-minute window (fallback / legacy use only).

    Prefer window_from_round() when PancakeSwap round data is available,
    as it uses the contract's actual start_ts and lock_ts.

    BNB Up/Down 5mn windows are aligned to UTC 5-minute marks:
    00:00, 00:05, 00:10, ...

    Returns:
        WindowInfo with start/end timestamps and seconds remaining.
    """
    if now is None:
        now = time.time()

    window_duration = 300  # 5 minutes
    window_start = int(now / window_duration) * window_duration
    window_end = window_start + window_duration
    seconds_remaining = window_end - now
    window_index = int(window_start / window_duration)

    return WindowInfo(
        window_start_ts=float(window_start),
        window_end_ts=float(window_end),
        seconds_remaining=seconds_remaining,
        window_index=window_index,
    )


def compute_momentum(prices: list[float]) -> float:
    """
    Compute simple momentum: (last_price / first_price) - 1.

    Args:
        prices: List of prices in chronological order.

    Returns:
        Momentum as a fraction (e.g., 0.005 = +0.5%).
        Returns 0.0 if fewer than 2 prices.
    """
    if len(prices) < 2:
        return 0.0
    return (prices[-1] / prices[0]) - 1.0


def compute_volatility(prices: list[float]) -> float:
    """
    Compute realized volatility (std dev of log returns).

    Args:
        prices: List of prices in chronological order.

    Returns:
        Annualized volatility estimate (per-observation std dev here).
        Returns 0.0 if fewer than 3 prices.
    """
    if len(prices) < 3:
        return 0.0
    log_returns = np.diff(np.log(prices))
    return float(np.std(log_returns))


def estimate_p_up_momentum(
    prices: list[float],
    window_seconds: float = 300.0,
    seconds_remaining: float = 60.0,
    n_simulations: int = 500,
) -> float:
    """
    Estimate P(BNB price at window end > BNB price at window start).

    Method: Geometric Brownian Motion (GBM) Monte Carlo projection.

    Uses the observed drift (momentum) and volatility over the current window
    to simulate the remaining price path.

    Args:
        prices: Price series for the current window.
        window_seconds: Total window duration in seconds.
        seconds_remaining: Seconds until window end.
        n_simulations: Number of Monte Carlo paths.

    Returns:
        Probability that BNB ends the window above its opening price.
        Returns 0.5 if insufficient data.
    """
    if len(prices) < 5:
        logger.debug("Insufficient price data for GBM — returning 0.5")
        return 0.5

    # Observed drift and vol over the window so far
    log_returns = np.diff(np.log(prices))
    if len(log_returns) == 0:
        return 0.5

    mu = float(np.mean(log_returns))       # Per-observation drift
    sigma = float(np.std(log_returns))     # Per-observation vol

    if sigma == 0:
        # No volatility observed → not enough info for a strong signal
        # Slight bias toward current direction, but never certainty
        if prices[-1] > prices[0]:
            return 0.6
        elif prices[-1] < prices[0]:
            return 0.4
        else:
            return 0.5

    current_price = prices[-1]
    opening_price = prices[0]

    # Number of remaining "steps" — approximate 1 step per second
    dt = 1.0  # 1 second per step
    steps = max(1, int(seconds_remaining))

    # Monte Carlo: simulate remaining price paths
    rng = np.random.default_rng(seed=None)
    z = rng.standard_normal((n_simulations, steps))
    log_path = (mu - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * z
    cumulative_log_returns = np.sum(log_path, axis=1)
    final_prices = current_price * np.exp(cumulative_log_returns)

    # P(Up) = fraction of paths where final price > opening price
    p_up_raw = float(np.mean(final_prices > opening_price))

    # Clamp to [0.20, 0.80] — force humility, avoid near-certain bets on 5mn crypto
    p_up = max(0.20, min(0.80, p_up_raw))

    logger.debug(
        f"GBM estimate: μ={mu:.6f} σ={sigma:.6f} "
        f"steps={steps} P(Up)={p_up:.3f} (raw={p_up_raw:.3f})"
    )
    return p_up


def compute_edge(p_up: float, yes_price: float) -> tuple[float, str]:
    """
    Compute the edge of a potential trade.

    Edge = |P(Up) - yes_price| — difference between our estimate and market price.
    Side = "YES" if we think it'll go up more than the market, "NO" otherwise.

    Args:
        p_up: Our estimated probability that BNB goes up.
        yes_price: Polymarket's YES price (= market-implied P(Up)).

    Returns:
        (edge, side) — edge as a positive float, side as "YES" or "NO".
    """
    if p_up > yes_price:
        return p_up - yes_price, "YES"
    else:
        return yes_price - p_up, "NO"


def kelly_fraction(p: float, odds: float = 1.0) -> float:
    """
    Compute the Kelly fraction for a binary bet.

    Kelly formula: f = p - q/b
    For a binary market with odds b (payout per unit risked = 1/price - 1):

    If YES at price `yes_price`:
      b = (1 - yes_price) / yes_price  (net profit per unit staked)
      f = (p * b - (1-p)) / b = (p*b - q) / b

    Args:
        p: Our estimated probability of winning.
        odds: Net odds (b = payout per unit risked, b=1.0 means evens).

    Returns:
        Kelly fraction (can be negative → no bet).
    """
    q = 1.0 - p
    if odds <= 0:
        return 0.0
    return (p * odds - q) / odds


def compute_position_size(
    edge: float,
    p_up: float,
    side: str,
    yes_price: float,
    bankroll: float,
    kelly_fraction_cap: float = 0.25,
    max_usdc: float = 50.0,
) -> tuple[float, float]:
    """
    Compute recommended position size using fractional Kelly.

    Args:
        edge: Our edge (|P(Up) - yes_price|).
        p_up: Our P(Up) estimate.
        side: "YES" or "NO".
        yes_price: Market YES price.
        bankroll: Current paper trading bankroll in USDC.
        kelly_fraction_cap: Maximum fraction of Kelly to use (default 25%).
        max_usdc: Hard cap on position size in USDC.

    Returns:
        (raw_kelly, position_size_usdc)
    """
    if side == "YES":
        p_win = p_up
        price = yes_price
    else:
        p_win = 1.0 - p_up
        price = 1.0 - yes_price

    # Net odds: if I pay `price` per share, I win (1 - price) per share
    if price <= 0 or price >= 1:
        return 0.0, 0.0

    b = (1.0 - price) / price  # Net odds
    raw_k = kelly_fraction(p_win, b)

    if raw_k <= 0:
        return raw_k, 0.0  # No edge or negative edge

    # Apply Kelly fraction cap
    frac = min(raw_k, kelly_fraction_cap)
    position_size = min(bankroll * frac, max_usdc)
    position_size = max(0.0, round(position_size, 2))

    return raw_k, position_size


# ─────────────────────────────────────────────────────────────────────────────
# Strategy engine
# ─────────────────────────────────────────────────────────────────────────────

class Strategy:
    """
    Last-Second Momentum Strategy for BNB Up/Down 5mn.

    Workflow:
    1. Called periodically by main loop with current price data + order book.
    2. Checks if we're in the entry window (last 60s).
    3. Estimates P(Up) via GBM Monte Carlo.
    4. Computes edge vs Polymarket price.
    5. Returns a Signal if edge exceeds threshold.
    """

    FAIR_ODDS_PRICE = 0.50  # Neutral price used when use_fair_odds=True

    def __init__(self, config: dict):
        cfg = config.get("strategy", {})
        self.edge_threshold = cfg.get("edge_threshold", 0.05)
        self.kelly_fraction_cap = cfg.get("kelly_fraction", 0.25)
        self.max_position_usdc = cfg.get("max_position_usdc", 50.0)
        self.entry_window_seconds = cfg.get("entry_window_seconds", 60)
        self.min_prob_diff = cfg.get("min_prob_diff", 0.03)
        self.bankroll = cfg.get("starting_bankroll_usdc", 1000.0)
        self.use_fair_odds = cfg.get("use_fair_odds", True)

        pcfg = config.get("pancake", {})
        self.max_bet_share_of_side = pcfg.get("max_bet_share_of_side", 0.10)
        self.min_pool_bnb = pcfg.get("min_pool_bnb", 5.0)

    def update_bankroll(self, new_bankroll: float):
        """Update the current bankroll after PnL changes."""
        self.bankroll = new_bankroll
        self.last_skip_reason: Optional[str] = None  # Set when evaluate() returns None

    def evaluate(
        self,
        prices: list[float],
        yes_price: float,
        window: WindowInfo,
        is_mock_data: bool = False,
        pool_total_bnb: float = 0.0,
        pool_bull_bnb: float = 0.0,
        pool_bear_bnb: float = 0.0,
    ) -> Optional[Signal]:
        """
        Evaluate whether to generate a trading signal.

        Args:
            prices: BNB price series for the current window.
            yes_price: Polymarket's current YES price.
            window: Current window information.
            is_mock_data: Whether the order book data is mock.
            pool_total_bnb: Total BNB in the pool (for size filter, only used when use_fair_odds=False).
            pool_bull_bnb: BNB on the bull side of the pool.
            pool_bear_bnb: BNB on the bear side of the pool.

        Returns:
            Signal if conditions met, None otherwise.
            When returning None, self.last_skip_reason is set with a human-readable reason.
        """
        self.last_skip_reason = None

        # Only trade in the last N seconds of the window
        if not window.is_entry_window and window.seconds_remaining > self.entry_window_seconds:
            logger.debug(
                f"Not in entry window (remaining={window.seconds_remaining:.1f}s)"
            )
            return None

        if len(prices) < 5:
            self.last_skip_reason = f"⏸ Not enough price data ({len(prices)} pts)"
            logger.debug("Insufficient price data for strategy evaluation.")
            return None

        # Estimate P(Up) via GBM Monte Carlo
        p_up = estimate_p_up_momentum(
            prices=prices,
            window_seconds=300.0,
            seconds_remaining=window.seconds_remaining,
        )

        # Pool quality filters (only when trading against real pool prices)
        if not self.use_fair_odds:
            if pool_total_bnb < self.min_pool_bnb:
                self.last_skip_reason = f"⏸ Pool too small ({pool_total_bnb:.2f} BNB < {self.min_pool_bnb:.1f} min)"
                logger.info(
                    f"Pool too small: {pool_total_bnb:.3f} BNB (min={self.min_pool_bnb:.1f}) — skipping"
                )
                return None

        # Fair-odds mode: use 0.50 as the reference price regardless of pool
        # This avoids fictitious PnL from 99/1 pool imbalances
        if self.use_fair_odds:
            effective_yes_price = self.FAIR_ODDS_PRICE
            if yes_price != self.FAIR_ODDS_PRICE:
                logger.info(
                    f"[INFO ONLY] Pool yes_price={yes_price:.4f} "
                    f"(ignored — use_fair_odds=true, trading at {self.FAIR_ODDS_PRICE:.2f})"
                )
        else:
            effective_yes_price = yes_price

        # Compute edge using effective price (fair odds or pool price)
        edge, side = compute_edge(p_up, effective_yes_price)

        logger.info(
            f"Strategy eval: P(Up)={p_up:.3f} | "
            f"effective_price={effective_yes_price:.3f} | "
            f"edge={edge:.3f} | side={side} | remaining={window.seconds_remaining:.1f}s"
        )

        # Check if edge exceeds threshold (strict >)
        if edge <= self.edge_threshold:
            self.last_skip_reason = f"⏸ Edge too low ({edge:.3f} ≤ {self.edge_threshold:.2f}) | P(Up)={p_up:.2f} | {side}"
            logger.debug(f"Edge {edge:.3f} < threshold {self.edge_threshold:.3f} — no signal")
            return None

        # Compute position size using effective price
        raw_k, pos_size = compute_position_size(
            edge=edge,
            p_up=p_up,
            side=side,
            yes_price=effective_yes_price,
            bankroll=self.bankroll,
            kelly_fraction_cap=self.kelly_fraction_cap,
            max_usdc=self.max_position_usdc,
        )

        if pos_size <= 0:
            logger.debug("Position size is 0 — no signal")
            return None

        if not self.use_fair_odds and prices:
            # Check opposite side has liquidity (no opponent = no profit even if we win)
            opposite_bnb = pool_bear_bnb if side == "YES" else pool_bull_bnb
            if opposite_bnb < 0.01:
                self.last_skip_reason = f"⏸ No counterparty ({'BEAR' if side == 'YES' else 'BULL'} side empty)"
                logger.info(
                    f"Opposite side empty: {'BEAR' if side == 'YES' else 'BULL'} = "
                    f"{opposite_bnb:.4f} BNB — no profit possible, skipping"
                )
                return None

            bet_bnb = pos_size / prices[-1]  # approximate BNB equivalent
            side_bnb = pool_bull_bnb if side == "YES" else pool_bear_bnb
            if side_bnb > 0 and bet_bnb / side_bnb > self.max_bet_share_of_side:
                self.last_skip_reason = f"⏸ Bet too large ({bet_bnb:.3f} BNB = {bet_bnb/side_bnb:.0%} of {side} side)"
                logger.info(
                    f"Bet too large for side: {bet_bnb:.4f} BNB = "
                    f"{bet_bnb/side_bnb:.1%} of {side} side ({side_bnb:.4f} BNB) "
                    f"(max={self.max_bet_share_of_side:.0%}) — skipping"
                )
                return None

        signal = Signal(
            side=side,
            edge=edge,
            p_up=p_up,
            yes_price=effective_yes_price,
            kelly_fraction=raw_k,
            position_size_usdc=pos_size,
            timestamp=time.time(),
            is_mock=is_mock_data,
        )

        logger.info(f"🎯 Signal generated: {signal}")
        return signal
